quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:page>', views.main, name='main_paginate'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name = 'quote'),
    path('author/<str:fullname>/', views.author_about, name='author_fullname'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quoteapp/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=25, null=False, unique=True)
    born_date = models.CharField(max_length=25, null=True)
    born_location = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)

    def __str__(self):
        return f"{self.fullname}"
    
class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField()

    def __str__(self):
        return f"{self.quote}"
    

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, MultipleChoiceField, ModelChoiceField, Select , MultipleHiddenInput
from .models import Author, Quote


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    born_date = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    born_location = CharField(min_length=3, max_length=100, required=True, widget=TextInput())
    description = CharField(required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(ModelForm):
    tags = CharField(max_length=100, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all(), widget=Select())
    quote = CharField(required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['tags', 'author', 'quote']
    
    

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/quoteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .forms import AuthorForm, QuoteForm
from .models import Author, Tag, Quote

# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all()
    authors = Author.objects.all()
    tags = Tag.objects.all()
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quoteapp/index.html', {'quotes': quotes_on_page, 'authors': authors, 'tags': tags})


def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})


def quote(request):
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        
        if form.is_valid():
            new_quote = form.save(commit=False)  # Создаем объект цитаты, но пока не сохраняем
            tags_input = form.cleaned_data['tags']  # Введенные пользователем теги

            tags_list = [tag.strip() for tag in tags_input.split(',')]  # Разделяем теги по запятой

            # Сохраняем цитату
            new_quote.author = form.cleaned_data['author']
            new_quote.save()

            # Добавляем теги, создавая их при необходимости
            for tag_name in tags_list:
                tag, created = Tag.objects.get_or_create(name=tag_name)
                new_quote.tags.add(tag)
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"authors": authors, 'form': form})

    return render(request, 'quoteapp/quote.html', {"authors": authors, 'form': QuoteForm()})

def author_about(request, fullname):
    author = get_object_or_404(Author, fullname=fullname)
    return render(request, 'quoteapp/author_about.html', {'author': author})

quotes/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm, LoginForm

# Create your views here.
def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quoteapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quoteapp:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quoteapp:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quoteapp:main')

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author name:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the born date author:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the born location author:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the description author:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quoteapp/templates/quoteapp/author_about.html
{% extends "quoteapp/base.html" %}


{% block content %}

<h1>{{author.fullname}}</h1>
<p><b>Born:</b> {{author.born_date}}</p>
<p><b>Born location:</b> {{author.born_location}}</p>
<p><b>Description:</b> {{author.description}}</p>

{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Quotes to Scrape</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            <ul>
                <li><a href="/" role="button"> Go back to the main page </a></li>
            </ul>
        </nav>
        {% block content %} {% endblock %}
    </main>
</body>

</html>

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Quotes to Scrape</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>

<body>
    <main class="container">
        <h1><a href="/">Quotes to Scrape</a></h1>
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href= "{% url 'quoteapp:author' %}" role="button"> Add author </a></li>
            <li><a href="{% url 'quoteapp:quote' %}" role="button"> Add quote </a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <nav style="padding-left: 800px; text-align: right;">
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
        </nav>
            
        {% endif %}
    </nav>
    {% for quote in quotes %}
    
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.quote }}</span>
        <div><span>by author <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
            <a href="{% url 'quoteapp:author_fullname' quote.author.fullname %}">(about)</a>
        </span>
        </div class="tags">
            tags:
            {% for tag in quote.tags.all %}
                {{ tag.name }}
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
        
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disable {% endif %}"
                href="{% if quotes.has_previous %} {% url 'quoteapp:main_paginate' quotes.previous_page_number %} {% else%} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>
        
        
            <li class="next">
                <a class="{% if not quotes.has_next %} disable {% endif %}"
                href="{% if quotes.has_next %} {% url 'quoteapp:main_paginate' quotes.next_page_number %} {% else%} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
        
        </ul>
    </nav>
    </main>
</body>

</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter tags:
            {{form.tags}}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div style="padding: 10px">
        <label>Select author:
            <select name="author" multiple="multiple" required>
                {% for author in authors %}
                <option value="{{author.pk}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter quote:
            {{form.quote}}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/login.html
{% extends "quoteapp/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/password_reset.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset complete!</h2>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
{% autoescape off %}

<body>
    <p>Hi {{ user.username }},</p>
    <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
    <p>
        <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
            {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
        </a>
    </p>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Thanks,</p>
    <p>The Our Team</p>
    {% endautoescape %}
    

quotes/users/templates/users/signup.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}